name: "coordinator"
mode: "release"
version: "v0.0.1"
start_time: "2024-01-23"

log:
  level: "info"
  filename: "coordinator.log"
  max_size: 200
  max_age: 30
  max_backups: 7

cluster:
  hosts:
    - "peter@192.168.31.150"
    - "peter@192.168.31.170"
  password: "123456"
  projects_path: "/home/peter/Projects/"
  go_build_path: "/tmp/go-build/"

redis:
  host: ""
  port: 6379
  password: ""
  db: 0
  pool_size: 100

asynq:
  host: ""
  port: 6379
  password: ""
  concurrency: 1