name: "master"
mode: "release"
version: "v0.0.1"
start_time: "2024-01-23"

log:
  level: "info"
  filename: "master.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: 127.0.0.1
  port: 3306
  user: "root"
  password: "123456"
  dbname: "distgo"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 100

asynq:
  host: 127.0.0.1
  port: 6379
  password: ""
  concurrency: 1